
DROP TABLE IF EXISTS passwords;

CREATE TABLE passwords (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  website TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
